######################################################################
# Automatically generated by qmake (2.01a) lun. févr. 9 16:49:10 2009
######################################################################

TEMPLATE = app
TARGET = kiess
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += src/network/kiessxmpp.h src/network/kiessxmppmechanism.h
SOURCES += src/network/kiessxmpp.cpp src/network/kiessxmppmechanism.cpp src/main.cpp

QT += network
