Board: kCardItem Class Reference
kCardItem Class Reference
#include <kCardItem.h>
Signals
void returnCardItem (kCardItem *)
Public Member Functions
kCardItem (const QRectF &rect, const QBrush &brush)
virtual ~kCardItem ()
virtual QRectF boundingRect () const
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *options, QWidget *widget)
qreal opacity () const
void setOpacity (qreal opacity)
void setPixmap (const QPixmap &pixmap)
Set the cardItem pixmap.
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Private Attributes
QBrush _mBrush
qreal _mLastVal
qreal _mOpacity
QPixmap _mPixmap
QPixmap _mSourcePixmap
Detailed Description
Definition at line 10 of file kCardItem.h.
Constructor & Destructor Documentation
kCardItem::kCardItem (const QRectF & rect, const QBrush & brush)
Definition at line 6 of file kCardItem.cpp.
kCardItem::~kCardItem () [virtual]
Definition at line 15 of file kCardItem.cpp.
Member Function Documentation
QRectF kCardItem::boundingRect () const [virtual]
Definition at line 19 of file kCardItem.cpp.
void kCardItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * options, QWidget * widget) [virtual]
Definition at line 26 of file kCardItem.cpp.
References _mBrush, _mLastVal, _mPixmap, and opacity().
qreal kCardItem::opacity () const
Definition at line 50 of file kCardItem.cpp.
References _mOpacity, and opacity().
Referenced by opacity(), and paint().
void kCardItem::setOpacity (qreal opacity)
Definition at line 56 of file kCardItem.cpp.
References _mOpacity.
void kCardItem::setPixmap (const QPixmap & pixmap)
Set the cardItem pixmap.
Parameters:
pixmap Pixmap to give
Permuts between null pixmap and source pixmap when card is folded
Definition at line 71 of file kCardItem.cpp.
References _mPixmap, and _mSourcePixmap.
Referenced by kBoard::createItems(), and keyPressEvent().
void kCardItem::keyPressEvent (QKeyEvent * event) [protected]
Definition at line 87 of file kCardItem.cpp.
References setPixmap().
void kCardItem::keyReleaseEvent (QKeyEvent * event) [protected]
Definition at line 96 of file kCardItem.cpp.
void kCardItem::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 104 of file kCardItem.cpp.
References returnCardItem().
void kCardItem::returnCardItem (kCardItem *) [signal]
Referenced by mousePressEvent().
Member Data Documentation
QBrush kCardItem::_mBrush [private]
Definition at line 30 of file kCardItem.h.
Referenced by paint().
qreal kCardItem::_mLastVal [private]
Definition at line 31 of file kCardItem.h.
Referenced by paint().
qreal kCardItem::_mOpacity [private]
Definition at line 32 of file kCardItem.h.
Referenced by opacity(), and setOpacity().
QPixmap kCardItem::_mPixmap [private]
Definition at line 33 of file kCardItem.h.
Referenced by paint(), and setPixmap().
QPixmap kCardItem::_mSourcePixmap [private]
Definition at line 34 of file kCardItem.h.
Referenced by setPixmap().
The documentation for this class was generated from the following files:
Z:/kiess/trunk/src/board/kCardItem.h
Z:/kiess/trunk/src/board/kCardItem.cpp