Board: kBoard Class Reference
kBoard Class Reference
#include <kBoard.h>
Public Member Functions
kBoard (const int &gridX=5, const int &gridY=5, QWidget *parent=0)
virtual ~kBoard ()
virtual QSize sizeHint () const
Protected Member Functions
void resizeEvent (QResizeEvent *event)
Private Slots
void selectedCardItem (kCardItem *)
Selected the cardItem after mousePressEvent received by teh cardItem.
void updateSelectionStep (qreal val)
Private Member Functions
void createItems ()
Create all items (Board and cards.
void createScene ()
Create environment.
void initBoardParameters ()
Initailization of the board.
QPointF posForLocation (int x, int y) const
void setCurrentItem (int x, int y, bool animate)
Move the _mSelectionItem to the selected cardItem.
Private Attributes
QPointF _mEndPos
QPointF _mStartPos
QTimeLine * _mFlipTimeLine
QTimeLine * _mSelectionTimeLine
QSize _mGridSize
kCardItem * _mContainerItem
kCardItem * _mSelectionItem
QMap< int, QMap< int,
kCardItem * > > _mItems
QGraphicsScene * _mScene
int _mSelectedX
int _mSelectedY
Detailed Description
Definition at line 10 of file kBoard.h.
Constructor & Destructor Documentation
kBoard::kBoard (const int & gridX = 5, const int & gridY = 5, QWidget * parent = 0)
Definition at line 8 of file kBoard.cpp.
References _mFlipTimeLine, _mSelectionTimeLine, createItems(), createScene(), initBoardParameters(), and updateSelectionStep().
kBoard::~kBoard () [virtual]
Definition at line 28 of file kBoard.cpp.
References _mContainerItem, and _mItems.
Member Function Documentation
QSize kBoard::sizeHint () const [virtual]
Definition at line 42 of file kBoard.cpp.
void kBoard::createItems () [private]
Create all items (Board and cards.
Definition at line 54 of file kBoard.cpp.
References _mContainerItem, _mGridSize, _mItems, _mSelectionItem, posForLocation(), selectedCardItem(), setCurrentItem(), and kCardItem::setPixmap().
Referenced by kBoard().
void kBoard::createScene () [private]
Create environment.
Definition at line 84 of file kBoard.cpp.
References _mContainerItem, _mGridSize, and _mScene.
Referenced by kBoard().
void kBoard::initBoardParameters () [private]
Initailization of the board.
Definition at line 102 of file kBoard.cpp.
Referenced by kBoard().
QPointF kBoard::posForLocation (int x, int y) const [private]
Definition at line 119 of file kBoard.cpp.
References _mGridSize.
Referenced by createItems(), and setCurrentItem().
void kBoard::setCurrentItem (int x, int y, bool animate) [private]
Move the _mSelectionItem to the selected cardItem.
Parameters:
x x coordinate (in the grid).
y y coordinate (in the grid).
animate Animation
The real x,y coordinate are computed from the following x,y coordinate in the grid referential.
Definition at line 140 of file kBoard.cpp.
References _mEndPos, _mItems, _mSelectionItem, _mSelectionTimeLine, _mStartPos, and posForLocation().
Referenced by createItems(), and selectedCardItem().
void kBoard::selectedCardItem (kCardItem * item) [private, slot]
Selected the cardItem after mousePressEvent received by teh cardItem.
Parameters:
kCardItem* item Item selected by mousePressEvent
The method iterates in all items in _mItems. if item found, item is selected.
Definition at line 170 of file kBoard.cpp.
References _mGridSize, _mItems, _mSelectedX, _mSelectedY, and setCurrentItem().
Referenced by createItems().
void kBoard::updateSelectionStep (qreal val) [private, slot]
Definition at line 189 of file kBoard.cpp.
References _mEndPos, _mSelectionItem, and _mStartPos.
Referenced by kBoard().
void kBoard::resizeEvent (QResizeEvent * event) [protected]
Definition at line 197 of file kBoard.cpp.
References _mScene.
Member Data Documentation
QPointF kBoard::_mEndPos [private]
Definition at line 44 of file kBoard.h.
Referenced by setCurrentItem(), and updateSelectionStep().
QPointF kBoard::_mStartPos [private]
Definition at line 45 of file kBoard.h.
Referenced by setCurrentItem(), and updateSelectionStep().
QTimeLine* kBoard::_mFlipTimeLine [private]
Definition at line 46 of file kBoard.h.
Referenced by kBoard().
QTimeLine* kBoard::_mSelectionTimeLine [private]
Definition at line 47 of file kBoard.h.
Referenced by kBoard(), and setCurrentItem().
QSize kBoard::_mGridSize [private]
Definition at line 50 of file kBoard.h.
Referenced by createItems(), createScene(), posForLocation(), and selectedCardItem().
kCardItem* kBoard::_mContainerItem [private]
Definition at line 53 of file kBoard.h.
Referenced by createItems(), createScene(), and ~kBoard().
kCardItem* kBoard::_mSelectionItem [private]
Definition at line 54 of file kBoard.h.
Referenced by createItems(), setCurrentItem(), and updateSelectionStep().
QMap<int, QMap<int, kCardItem*> > kBoard::_mItems [private]
Definition at line 55 of file kBoard.h.
Referenced by createItems(), selectedCardItem(), setCurrentItem(), and ~kBoard().
QGraphicsScene* kBoard::_mScene [private]
Definition at line 58 of file kBoard.h.
Referenced by createScene(), and resizeEvent().
int kBoard::_mSelectedX [private]
Definition at line 61 of file kBoard.h.
Referenced by selectedCardItem().
int kBoard::_mSelectedY [private]
Definition at line 61 of file kBoard.h.
Referenced by selectedCardItem().
The documentation for this class was generated from the following files:
Z:/kiess/trunk/src/board/kBoard.h
Z:/kiess/trunk/src/board/kBoard.cpp